gui:
  theme:
    lightTheme: false
    defaultFgColor:
      - "#cdd6f4"
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#6c7086"
    optionsTextColor:
      - "#bac2de"
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#45475a"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#a6e3a1"
    unstagedChangesColor:
      - "#f38ba8"

